#!/bin/bash

ACOMPC="/Users/apple/Desktop/air_20/bin/acompc"
ADT="/Users/apple/Desktop/air_20/bin/adt"
VERSION="FWSoundMixer/1.0"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

SWFVERSION=18

INCLUDE_CLASSES="com.rainbowcreatures.FWSoundMixer com.rainbowcreatures.swf.Dummy com.rainbowcreatures.FWSound"
NAME="FWSoundMixerANE"

echo "Generating SWC"
$ACOMPC -source-path="/Users/apple/Desktop/Flash_Native_Extensions/FlashyWrappers_SVN/rainbowcreatures_flashywrappers/FWSoundMixer/iOS/" -include-classes $INCLUDE_CLASSES -swf-version=$SWFVERSION -target-player=11.5 -output $NAME.swc
sleep 3

cp $NAME.swc iOS/ane/$NAME.swc
echo "GENERATING LIBRARY from SWC"
unzip -q -o $NAME.swc -d iOS
sleep 2
[[ -f "catalog.xml" ]] && rm -f "catalog.xml"

echo "GENERATING ANE"
$ADT -package -target ane iOS/ane/$NAME.ane $DIR/iOS/extension.xml -swc $NAME.swc -platform iPhone-ARM -C iOS library.swf -C iOS/Release lib$NAME.a -platformoptions iOS/platform.xml
sleep 2
[[ -f "library.swf" ]] && rm -f "library.swf"

rm *.swc
echo "DONE!"
